float:
  any:
  - base_args: ['@metric']
    constructor: PGVector
    disabled: false
    docker_tag: ann-benchmarks-pgvector-hnsw
    module: ann_benchmarks.algorithms.pgvector_hnsw
    name: pgvector_hnsw
    run_groups:
      M-12:
        arg_groups: [{M: 12, efConstruction: 60}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-16:
        arg_groups: [{M: 16, efConstruction: 40}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-24:
        arg_groups: [{M: 24, efConstruction: 40}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
